In [322]:
import pandas as pd
from pathlib import Path

In [375]:

# ── Paths ────────────────────────────────────────────────────────────────────
raw_path  = Path(r"C:\Users\snaja\OneDrive\defaidtics\data\raw\wb\gdp_wb.csv")
save_path = Path(r"C:\Users\snaja\OneDrive\defaidtics\data\clean\wb\gdp_wb_clean.csv")

# ── Load ────────────────────────────────────────────────────────────────────
df = pd.read_csv(raw_path)

In [376]:
df.columns

Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '1990 [YR1990]', '1991 [YR1991]', '1992 [YR1992]', '1993 [YR1993]',
       '1994 [YR1994]', '1995 [YR1995]', '1996 [YR1996]', '1997 [YR1997]',
       '1998 [YR1998]', '1999 [YR1999]', '2000 [YR2000]', '2001 [YR2001]',
       '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]', '2005 [YR2005]',
       '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]', '2009 [YR2009]',
       '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]', '2013 [YR2013]',
       '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]', '2017 [YR2017]',
       '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]', '2021 [YR2021]',
       '2022 [YR2022]', '2023 [YR2023]', '2024 [YR2024]'],
      dtype='object')

In [377]:
# Rename the column for consistency
df = df.rename(columns={"Country Name": "Country"})
df.head()

,Country,Country Code,Series Name,Series Code,1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],1995 [YR1995],...,2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,United Arab Emirates,ARE,GDP (constant 2015 US$),NY.GDP.MKTP.KD,127141173333.666,128234691613.625,132524071337.561,134195452926.099,143449770711.842,153043528503.787,...,370275469560.166,390868305567.669,393741456191.578,398914879841.349,403336245487.99,383342656303.629,400036290943.156,430077804411.91,445641058027.777,..
1,Afghanistan,AFG,GDP (constant 2015 US$),NY.GDP.MKTP.KD,..,..,..,..,..,..,...,19134221644.7325,19566715174.1633,20084646751.4954,20323499020.3639,21118473702.3471,20621957125.2077,16345202562.5485,15325233810.1388,15740683549.2312,..
2,Africa Eastern and Southern,AFE,GDP (constant 2015 US$),NY.GDP.MKTP.KD,399493845643.486,399103504456.785,389737439405.34,387402501872.876,394875369504.144,411789546698.154,...,898277807343.005,917992857347,942636770833.106,967773422990.44,989009454513.18,960681330778.443,1004645882051.53,1040349774688.04,1064487323079.33,..
3,Africa Western and Central,AFW,GDP (constant 2015 US$),NY.GDP.MKTP.KD,261338873733.521,263994746904.169,270256324506.739,266725339390.886,265844227917.502,270836441550.617,...,771766914345.161,773007777373.463,790708189694.781,813201903750.811,839491928524.291,831063479599.043,864618743927.334,897385026208.953,927489896195.979,..
4,Albania,ALB,GDP (constant 2015 US$),NY.GDP.MKTP.KD,5279160805.75993,3800882718.68776,3527709061.94659,3864937294.2247,4185837881.82175,4743489156.74337,...,11386853113.0189,11764325094.2129,12211675169.6845,12702504600.374,12964502337.0284,12534895529.6924,13659219676.8332,14318507636.8055,14882173624.9218,..

In [378]:
# Get unique country names
unique_countries = df['Country'].unique()
print(unique_countries)

['United Arab Emirates' 'Afghanistan' 'Africa Eastern and Southern'
 'Africa Western and Central' 'Albania' 'Algeria' 'American Samoa'
 'Andorra' 'Angola' 'Antigua and Barbuda' 'Arab World' 'Argentina'
 'Armenia' 'Aruba' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas, The'
 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin'
 'Bermuda' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'British Virgin Islands' 'Brunei Darussalam' 'Bulgaria' 'Burkina Faso'
 'Burundi' 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada'
 'Caribbean small states' 'Cayman Islands' 'Central African Republic'
 'Central Europe and the Baltics' 'Chad' 'Channel Islands' 'Chile' 'China'
 'Colombia' 'Comoros' 'Congo, Dem. Rep.' 'Congo, Rep.' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao' 'Cyprus' 'Czechia' 'Denmark'
 'Djibouti' 'Dominica' 'Dominican Republic' 'Early-demographic dividend'
 'East Asia & Pacific' 'East Asia & Pacific (excluding high income)'
 'East Asia & Pacific (IDA & IBRD countries)' 'Ecuador' 'Egypt, Arab Rep.'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Euro area' 'Europe & Central Asia'
 'Europe & Central Asia (excluding high income)'
 'Europe & Central Asia (IDA & IBRD countries)' 'European Union'
 'Faroe Islands' 'Fiji' 'Finland'
 'Fragile and conflict affected situations' 'France' 'French Polynesia'
 'Gabon' 'Gambia, The' 'Georgia' 'Germany' 'Ghana' 'Gibraltar' 'Greece'
 'Greenland' 'Grenada' 'Guam' 'Guatemala' 'Guinea' 'Guinea-Bissau'
 'Guyana' 'Haiti' 'Heavily indebted poor countries (HIPC)' 'High income'
 'Honduras' 'Hong Kong SAR, China' 'Hungary' 'IBRD only' 'Iceland'
 'IDA & IBRD total' 'IDA blend' 'IDA only' 'IDA total' 'India' 'Indonesia'
 'Iran, Islamic Rep.' 'Iraq' 'Ireland' 'Isle of Man' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati'
 "Korea, Dem. People's Rep." 'Korea, Rep.' 'Kosovo' 'Kuwait'
 'Kyrgyz Republic' 'Lao PDR' 'Late-demographic dividend'
 'Latin America & Caribbean'
 'Latin America & Caribbean (excluding high income)'
 'Latin America & the Caribbean (IDA & IBRD countries)' 'Latvia'
 'Least developed countries: UN classification' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Low & middle income'
 'Low income' 'Lower middle income' 'Luxembourg' 'Macao SAR, China'
 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Marshall Islands' 'Mauritania' 'Mauritius' 'Mexico'
 'Micronesia, Fed. Sts.' 'Middle East & North Africa'
 'Middle East & North Africa (excluding high income)'
 'Middle East & North Africa (IDA & IBRD countries)' 'Middle income'
 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco' 'Mozambique'
 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands' 'New Caledonia'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'North America'
 'North Macedonia' 'Northern Mariana Islands' 'Norway' 'Not classified'
 'OECD members' 'Oman' 'Other small states' 'Pacific island small states'
 'Pakistan' 'Palau' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Post-demographic dividend'
 'Pre-demographic dividend' 'Puerto Rico' 'Qatar' 'Romania'
 'Russian Federation' 'Rwanda' 'Samoa' 'San Marino'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Singapore' 'Sint Maarten (Dutch part)' 'Slovak Republic'
 'Slovenia' 'Small states' 'Solomon Islands' 'Somalia' 'South Africa'
 'South Asia' 'South Asia (IDA & IBRD)' 'South Sudan' 'Spain' 'Sri Lanka'
 'St. Kitts and Nevis' 'St. Lucia' 'St. Martin (French part)'
 'St. Vincent and the Grenadines' 'Sub-Saharan Africa'
 'Sub-Saharan Africa (excluding high income)'
 'Sub-Saharan Africa (IDA & IBRD countries)' 'Sudan' 'Suriname' 'Sweden'
 'Switzerland' 'Syrian Arab Republic' 'Tajikistan' 'Tanzania' 'Thailand'
 'Timor-Leste' 'Togo' 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkiye'
 'Turkmenistan' 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Kingdom' 'United States' 'Upper middle income' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Venezuela, RB' 'Viet Nam' 'Virgin Islands (U.S.)'
 'West Bank and Gaza' 'World' 'Yemen, Rep.' 'Zambia' 'Zimbabwe' nan
 'Data from database: World Development Indicators'
 'Last Updated: 04/15/2025']

In [379]:

# ── Rename year columns ──────────────────────────────────────────────────────
year_cols = [c for c in df.columns if c[:4].isdigit()]
df.rename(columns={c: c[:4] for c in year_cols}, inplace=True)

# ── Drop footer / empty rows (Country Code is NaN) ───────────────────────────
df = df[df["Country Code"].notna()].copy()

# ── Drop Series columns ──────────────────────────────────────────────────────
df.drop(columns=['Country Code',"1990", "1991", "Series Name", "Series Code", '2024'], inplace=True)
df.reset_index(drop=True, inplace=True)

In [380]:
df.head()

,Country,1992,1993,1994,1995,1996,1997,1998,1999,2000,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,United Arab Emirates,132524071337.561,134195452926.099,143449770711.842,153043528503.787,161917610688.198,175179308486.77,175690822156.071,180789745160.268,200410321454.247,...,346742821770.78,370275469560.166,390868305567.669,393741456191.578,398914879841.349,403336245487.99,383342656303.629,400036290943.156,430077804411.91,445641058027.777
1,Afghanistan,..,..,..,..,..,..,..,..,6206547590.07403,...,18860496494.0404,19134221644.7325,19566715174.1633,20084646751.4954,20323499020.3639,21118473702.3471,20621957125.2077,16345202562.5485,15325233810.1388,15740683549.2312
2,Africa Eastern and Southern,389737439405.34,387402501872.876,394875369504.144,411789546698.154,434240273307.563,450925028921.906,458826475384.177,470985014904.524,486126929267.789,...,872072576697.475,898277807343.005,917992857347,942636770833.106,967773422990.44,989009454513.18,960681330778.443,1004645882051.53,1040349774688.04,1064487323079.33
3,Africa Western and Central,270256324506.739,266725339390.886,265844227917.502,270836441550.617,283400368462.986,295896431520.044,306558488961.48,311259954479.919,323300981738.909,...,751328052455.902,771766914345.161,773007777373.463,790708189694.781,813201903750.811,839491928524.291,831063479599.043,864618743927.334,897385026208.953,927489896195.979
4,Albania,3527709061.94659,3864937294.2247,4185837881.82175,4743489156.74337,5175146643.27572,4610021453.80966,5017059783.31958,5663799108.52767,6057218861.96683,...,11139693788.8124,11386853113.0189,11764325094.2129,12211675169.6845,12702504600.374,12964502337.0284,12534895529.6924,13659219676.8332,14318507636.8055,14882173624.9218

In [381]:
# Get unique countries
unique_countries = df["Country"].unique()

print(unique_countries)

['United Arab Emirates' 'Afghanistan' 'Africa Eastern and Southern'
 'Africa Western and Central' 'Albania' 'Algeria' 'American Samoa'
 'Andorra' 'Angola' 'Antigua and Barbuda' 'Arab World' 'Argentina'
 'Armenia' 'Aruba' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas, The'
 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin'
 'Bermuda' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'British Virgin Islands' 'Brunei Darussalam' 'Bulgaria' 'Burkina Faso'
 'Burundi' 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada'
 'Caribbean small states' 'Cayman Islands' 'Central African Republic'
 'Central Europe and the Baltics' 'Chad' 'Channel Islands' 'Chile' 'China'
 'Colombia' 'Comoros' 'Congo, Dem. Rep.' 'Congo, Rep.' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao' 'Cyprus' 'Czechia' 'Denmark'
 'Djibouti' 'Dominica' 'Dominican Republic' 'Early-demographic dividend'
 'East Asia & Pacific' 'East Asia & Pacific (excluding high income)'
 'East Asia & Pacific (IDA & IBRD countries)' 'Ecuador' 'Egypt, Arab Rep.'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Euro area' 'Europe & Central Asia'
 'Europe & Central Asia (excluding high income)'
 'Europe & Central Asia (IDA & IBRD countries)' 'European Union'
 'Faroe Islands' 'Fiji' 'Finland'
 'Fragile and conflict affected situations' 'France' 'French Polynesia'
 'Gabon' 'Gambia, The' 'Georgia' 'Germany' 'Ghana' 'Gibraltar' 'Greece'
 'Greenland' 'Grenada' 'Guam' 'Guatemala' 'Guinea' 'Guinea-Bissau'
 'Guyana' 'Haiti' 'Heavily indebted poor countries (HIPC)' 'High income'
 'Honduras' 'Hong Kong SAR, China' 'Hungary' 'IBRD only' 'Iceland'
 'IDA & IBRD total' 'IDA blend' 'IDA only' 'IDA total' 'India' 'Indonesia'
 'Iran, Islamic Rep.' 'Iraq' 'Ireland' 'Isle of Man' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati'
 "Korea, Dem. People's Rep." 'Korea, Rep.' 'Kosovo' 'Kuwait'
 'Kyrgyz Republic' 'Lao PDR' 'Late-demographic dividend'
 'Latin America & Caribbean'
 'Latin America & Caribbean (excluding high income)'
 'Latin America & the Caribbean (IDA & IBRD countries)' 'Latvia'
 'Least developed countries: UN classification' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Low & middle income'
 'Low income' 'Lower middle income' 'Luxembourg' 'Macao SAR, China'
 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Marshall Islands' 'Mauritania' 'Mauritius' 'Mexico'
 'Micronesia, Fed. Sts.' 'Middle East & North Africa'
 'Middle East & North Africa (excluding high income)'
 'Middle East & North Africa (IDA & IBRD countries)' 'Middle income'
 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco' 'Mozambique'
 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands' 'New Caledonia'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'North America'
 'North Macedonia' 'Northern Mariana Islands' 'Norway' 'Not classified'
 'OECD members' 'Oman' 'Other small states' 'Pacific island small states'
 'Pakistan' 'Palau' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Post-demographic dividend'
 'Pre-demographic dividend' 'Puerto Rico' 'Qatar' 'Romania'
 'Russian Federation' 'Rwanda' 'Samoa' 'San Marino'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Singapore' 'Sint Maarten (Dutch part)' 'Slovak Republic'
 'Slovenia' 'Small states' 'Solomon Islands' 'Somalia' 'South Africa'
 'South Asia' 'South Asia (IDA & IBRD)' 'South Sudan' 'Spain' 'Sri Lanka'
 'St. Kitts and Nevis' 'St. Lucia' 'St. Martin (French part)'
 'St. Vincent and the Grenadines' 'Sub-Saharan Africa'
 'Sub-Saharan Africa (excluding high income)'
 'Sub-Saharan Africa (IDA & IBRD countries)' 'Sudan' 'Suriname' 'Sweden'
 'Switzerland' 'Syrian Arab Republic' 'Tajikistan' 'Tanzania' 'Thailand'
 'Timor-Leste' 'Togo' 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkiye'
 'Turkmenistan' 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Kingdom' 'United States' 'Upper middle income' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Venezuela, RB' 'Viet Nam' 'Virgin Islands (U.S.)'
 'West Bank and Gaza' 'World' 'Yemen, Rep.' 'Zambia' 'Zimbabwe']

In [382]:
# List of known aggregate/non-country entries to exclude
non_countries = [
    # Global/Income groups
    'World',
    'High income',
    'Low income',
    'Lower middle income',
    'Upper middle income',
    'Low & middle income',
    'Middle income',

    # Special classifications
    'Fragile and conflict affected situations',
    'Heavily indebted poor countries (HIPC)',
    'IDA only',
    'IDA blend',
    'IDA total',
    'IDA & IBRD total',
    'IBRD only',

    # Regional aggregates
    'European Union',
    'OECD members',
    'Caribbean small states',
    'Pacific island small states',
    'Other small states',
    'Small states',
    'Not classified',

    # Sub-regions
    'Sub-Saharan Africa',
    'Sub-Saharan Africa (excluding high income)',
    'Sub-Saharan Africa (IDA & IBRD countries)',
    'Latin America & Caribbean',
    'Latin America & Caribbean (excluding high income)',
    'Latin America & the Caribbean (IDA & IBRD countries)',
    'East Asia & Pacific',
    'East Asia & Pacific (excluding high income)',
    'East Asia & Pacific (IDA & IBRD countries)',
    'Europe & Central Asia',
    'Europe & Central Asia (excluding high income)',
    'Europe & Central Asia (IDA & IBRD countries)',
    'Middle East & North Africa',
    'Middle East & North Africa (excluding high income)',
    'Middle East & North Africa (IDA & IBRD countries)',
    'North America',

    # Demographic groups
    'Early-demographic dividend',
    'Late-demographic dividend',
    'Post-demographic dividend',
    'Pre-demographic dividend',

    # Territories and special areas
    'Channel Islands',
    'Isle of Man',
    'Jersey',
    'Guernsey',
    'Northern Mariana Islands',
    'Virgin Islands (U.S.)',
    'Puerto Rico',
    'Gibraltar',
    'Hong Kong SAR, China',
    'Macao SAR, China',
    'West Bank and Gaza',
    'Kosovo',
    'Sint Maarten (Dutch part)',
    'New Caledonia',

    # Added requested territories and regions
    'Arab World',                 # region, not country
    'American Samoa',             # US territory
    'British Virgin Islands',     # UK Overseas Territory
    'Cayman Islands',             # UK Overseas Territory
    'Curacao',                    # country within Kingdom of Netherlands
    'Faroe Islands',              # autonomous territory of Denmark
    'French Polynesia',           # overseas collectivity of France
    'Greenland',                  # autonomous territory of Denmark
    'Guam',                      # US territory
    'Marshall Islands',           # independent country in free association with US
    'Palau',                     # independent country in free association with US
    # 'Puerto Rico' already included above

    # Regional groupings
    'Least developed countries: UN classification',
    'South Asia',
    'South Asia (IDA & IBRD)',
    'Africa Eastern and Southern',
    'Africa Western and Central',
    'Central African Republic',  # <-- Only exclude if desired, as it's a country
    'Central Europe and the Baltics',

    # Additional territories/aggregates sometimes seen
    'Micronesia, Fed. Sts.',
    'European Union',
    'OECD',
    'Euro area',
    'World Bank high income',
    'World Bank low income',
    'World Bank middle income',
    'World Bank upper middle income',
    'World Bank lower middle income',

    # Other groupings
    'Fragile situations',
    'Small states',
]


# 1. Filter out non-countries
df_filtered = df[~df['Country'].isin(non_countries)].copy()


# Reset index so it goes from 0 to len(df)-1
df_filtered = df_filtered.reset_index(drop=True)

# 2. Normalize country names: strip whitespace and consistent capitalization
df_filtered['Country'] = df_filtered['Country'].str.strip()
df_filtered['Country'] = df_filtered['Country'].str.replace(' And ', ' and ', regex=False)
df_filtered['Country'] = df_filtered['Country'].str.replace(' Of ', ' of ', regex=False)
df_filtered['Country'] = df_filtered['Country'].str.replace(' Dr', ' DR', regex=False)

# 3. Manual fixes for spelling/formatting inconsistencies
df_filtered['Country'] = df_filtered['Country'].replace({
    'TÃ¼rkiye': 'Türkiye',
    'Tã¼rkiye': 'Türkiye',
    'Turkiye': 'Türkiye',
    "Cote D'Ivoire": "Cote d'Ivoire",
    'Bosnia And Herzegovina': 'Bosnia and Herzegovina',
    'Trinidad And Tobago': 'Trinidad and Tobago',
    'United States Of America': 'United States',
    'United States': 'United States',
    'Cape Verde': 'Cabo Verde',
    'Congo, DR': 'Congo, Dem. Rep.',
    'Congo, Republic': 'Congo, Rep.',
    'Korea, South': 'South Korea',
    'Korea, Rep.': 'South Korea',
    'Brunei Darussalam': 'Brunei',
    'Lao PDR': 'Laos',
    'Timor Leste': 'Timor-Leste',
    'Russian Federation': 'Russia',
    'Iran, Islamic Rep.': 'Iran',
    'Egypt, Arab Rep.': 'Egypt',
    'Slovak Republic': 'Slovakia',
    'Yemen, Rep.': 'Yemen',
    'Bahamas, The' : 'The Bahamas',
    'Venezuela, RB': 'Venezuela',
    'Viet Nam' : 'Vietnam',
    'Russian Federation': 'Russia',
    'Iran, Islamic Rep.': 'Iran',
    'Korea, Rep.': 'South Korea',
    "Korea, Dem. People's Rep.": 'North Korea',
    'Egypt, Arab Rep.': 'Egypt',
    'Lao PDR': 'Laos',
    'Venezuela, RB': 'Venezuela',
    'Slovak Republic': 'Slovakia',
    'Syrian Arab Republic': 'Syria',
    'Gambia, The': 'The Gambia',
    'Bahamas, The': 'The Bahamas',
    'Brunei Darussalam': 'Brunei',
    'Cabo Verde': 'Cape Verde',
    'Timor-Leste': 'Timor Leste',
    'Congo, Dem. Rep.': 'Congo (Kinshasa)',
    'Congo, Rep.': 'Congo (Brazzaville)',
    'Cote d\'Ivoire': 'Ivory Coast',

})

# 4. Convert year columns from object (string) to numeric (float), handling errors gracefully
years = [str(y) for y in range(1992, 2025)]
for year in years:
    if year in df_filtered.columns:
        df_filtered[year] = pd.to_numeric(df_filtered[year], errors='coerce')


# Now df is filtered and country names are standardized, ready for analysis

print(f"Data shape after filtering and cleaning: {df_filtered.shape}")
print("Unique countries after cleaning:", df_filtered['Country'].unique())

Data shape after filtering and cleaning: (193, 33)
Unique countries after cleaning: ['United Arab Emirates' 'Afghanistan' 'Albania' 'Algeria' 'Andorra'
 'Angola' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba' 'Australia'
 'Austria' 'Azerbaijan' 'The Bahamas' 'Bahrain' 'Bangladesh' 'Barbados'
 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Brunei' 'Bulgaria'
 'Burkina Faso' 'Burundi' 'Cape Verde' 'Cambodia' 'Cameroon' 'Canada'
 'Chad' 'Chile' 'China' 'Colombia' 'Comoros' 'Congo (Kinshasa)'
 'Congo (Brazzaville)' 'Costa Rica' 'Ivory Coast' 'Croatia' 'Cuba'
 'Cyprus' 'Czechia' 'Denmark' 'Djibouti' 'Dominica' 'Dominican Republic'
 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia'
 'Eswatini' 'Ethiopia' 'Fiji' 'Finland' 'France' 'Gabon' 'The Gambia'
 'Georgia' 'Germany' 'Ghana' 'Greece' 'Grenada' 'Guatemala' 'Guinea'
 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras' 'Hungary' 'Iceland' 'India'
 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan'
 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati' 'North Korea' 'South Korea'
 'Kuwait' 'Kyrgyz Republic' 'Laos' 'Latvia' 'Lebanon' 'Lesotho' 'Liberia'
 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg' 'Madagascar' 'Malawi'
 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Mauritania' 'Mauritius' 'Mexico'
 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco' 'Mozambique'
 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands' 'New Zealand'
 'Nicaragua' 'Niger' 'Nigeria' 'North Macedonia' 'Norway' 'Oman'
 'Pakistan' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines'
 'Poland' 'Portugal' 'Qatar' 'Romania' 'Russia' 'Rwanda' 'Samoa'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia'
 'Solomon Islands' 'Somalia' 'South Africa' 'South Sudan' 'Spain'
 'Sri Lanka' 'St. Kitts and Nevis' 'St. Lucia' 'St. Martin (French part)'
 'St. Vincent and the Grenadines' 'Sudan' 'Suriname' 'Sweden'
 'Switzerland' 'Syria' 'Tajikistan' 'Tanzania' 'Thailand' 'Timor Leste'
 'Togo' 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Türkiye' 'Turkmenistan'
 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine' 'United Kingdom'
 'United States' 'Uruguay' 'Uzbekistan' 'Vanuatu' 'Venezuela' 'Vietnam'
 'Yemen' 'Zambia' 'Zimbabwe']

In [383]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 33 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  193 non-null    object
 1   1992     182 non-null    float64
 2   1993     182 non-null    float64
 3   1994     182 non-null    float64
 4   1995     183 non-null    float64
 5   1996     183 non-null    float64
 6   1997     185 non-null    float64
 7   1998     185 non-null    float64
 8   1999     185 non-null    float64
 9   2000     186 non-null    float64
 10  2001     186 non-null    float64
 11  2002     186 non-null    float64
 12  2003     186 non-null    float64
 13  2004     186 non-null    float64
 14  2005     186 non-null    float64
 15  2006     186 non-null    float64
 16  2007     186 non-null    float64
 17  2008     187 non-null    float64
 18  2009     187 non-null    float64
 19  2010     187 non-null    float64
 20  2011     188 non-null    float64
 21  2012     187 non-null    float64
 22  2013     188 non-null    float64
 23  2014     188 non-null    float64
 24  2015     189 non-null    float64
 25  2016     187 non-null    float64
 26  2017     187 non-null    float64
 27  2018     187 non-null    float64
 28  2019     186 non-null    float64
 29  2020     186 non-null    float64
 30  2021     186 non-null    float64
 31  2022     186 non-null    float64
 32  2023     181 non-null    float64
dtypes: float64(32), object(1)
memory usage: 49.9+ KB

In [384]:
df_filtered.head(60)

,Country,1992,1993,1994,1995,1996,1997,1998,1999,2000,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,United Arab Emirates,1.325241e+11,1.341955e+11,1.434498e+11,1.530435e+11,1.619176e+11,1.751793e+11,1.756908e+11,1.807897e+11,2.004103e+11,...,3.467428e+11,3.702755e+11,3.908683e+11,3.937415e+11,3.989149e+11,4.033362e+11,3.833427e+11,4.000363e+11,4.300778e+11,4.456411e+11
1,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.206548e+09,...,1.886050e+10,1.913422e+10,1.956672e+10,2.008465e+10,2.032350e+10,2.111847e+10,2.062196e+10,1.634520e+10,1.532523e+10,1.574068e+10
2,Albania,3.527709e+09,3.864937e+09,4.185838e+09,4.743489e+09,5.175147e+09,4.610021e+09,5.017060e+09,5.663799e+09,6.057219e+09,...,1.113969e+10,1.138685e+10,1.176433e+10,1.221168e+10,1.270250e+10,1.296450e+10,1.253490e+10,1.365922e+10,1.431851e+10,1.488217e+10
3,Algeria,9.202645e+10,9.009389e+10,8.928305e+10,9.267580e+10,9.647551e+10,9.753674e+10,1.025111e+11,1.057915e+11,1.098116e+11,...,1.816801e+11,1.874939e+11,1.948061e+11,1.977282e+11,2.004964e+11,2.023009e+11,1.921858e+11,1.994889e+11,2.066705e+11,2.151440e+11
4,Andorra,1.695349e+09,1.677862e+09,1.717848e+09,1.765218e+09,1.847296e+09,2.014803e+09,2.079171e+09,2.164398e+09,2.240766e+09,...,2.750436e+09,2.789881e+09,2.893377e+09,2.903390e+09,2.949518e+09,3.008967e+09,2.672446e+09,2.893906e+09,3.170697e+09,3.252613e+09
5,Angola,2.631549e+10,2.000414e+10,2.027207e+10,2.331287e+10,2.647046e+10,2.839599e+10,2.972809e+10,3.037660e+10,3.130450e+10,...,8.965050e+10,9.049642e+10,8.816157e+10,8.803178e+10,8.687297e+10,8.626288e+10,8.139919e+10,8.237534e+10,8.488345e+10,8.573337e+10
6,Antigua and Barbuda,8.581153e+08,9.034261e+08,9.637381e+08,9.217252e+08,9.826039e+08,1.036364e+09,1.085397e+09,1.125640e+09,1.195469e+09,...,1.417274e+09,1.437756e+09,1.496700e+09,1.533569e+09,1.640201e+09,1.691054e+09,1.371776e+09,1.484149e+09,1.625386e+09,1.688159e+09
7,Argentina,3.131202e+11,3.388180e+11,3.585921e+11,3.483894e+11,3.676438e+11,3.974635e+11,4.127666e+11,3.987925e+11,3.956461e+11,...,5.789376e+11,5.947493e+11,5.823766e+11,5.987909e+11,5.831181e+11,5.714507e+11,5.148743e+11,5.686366e+11,5.986030e+11,5.889595e+11
8,Armenia,3.001096e+09,2.737000e+09,2.884798e+09,3.083849e+09,3.264729e+09,3.373153e+09,3.619394e+09,3.738834e+09,3.959425e+09,...,1.022610e+10,1.055334e+10,1.057444e+10,1.136753e+10,1.195864e+10,1.286750e+10,1.194104e+10,1.263362e+10,1.422545e+10,1.540616e+10
9,Aruba,1.908830e+09,2.048322e+09,2.216364e+09,2.272818e+09,2.299769e+09,2.461831e+09,2.510870e+09,2.541956e+09,2.735727e+09,...,2.981501e+09,2.962907e+09,3.013858e+09,3.226291e+09,3.303628e+09,3.229876e+09,2.383267e+09,2.958412e+09,3.210407e+09,3.347290e+09
10,Australia,6.297462e+11,6.552303e+11,6.813110e+11,7.077863e+11,7.351344e+11,7.639020e+11,7.995244e+11,8.397219e+11,8.726517e+11,...,1.322335e+12,1.351296e+12,1.388584e+12,1.420238e+12,1.461119e+12,1.492848e+12,1.491063e+12,1.522541e+12,1.587133e+12,1.641762e+12
11,Austria,2.527148e+11,2.540462e+11,2.601487e+11,2.670894e+11,2.730075e+11,2.788658e+11,2.886062e+11,2.994633e+11,3.090148e+11,...,3.746623e+11,3.795461e+11,3.875819e+11,3.963888e+11,4.062359e+11,4.133653e+11,3.872478e+11,4.058176e+11,4.272362e+11,4.231563e+11
12,Azerbaijan,1.555617e+10,1.196270e+10,9.606044e+09,8.472531e+09,8.582674e+09,9.080469e+09,9.988516e+09,1.072767e+10,1.191844e+10,...,5.250188e+10,5.307624e+10,5.143087e+10,5.153373e+10,5.230674e+10,5.361441e+10,5.130899e+10,5.419073e+10,5.674572e+10,5.738353e+10
13,The Bahamas,7.886417e+09,7.910691e+09,8.159792e+09,8.517090e+09,8.876811e+09,8.991123e+09,9.415216e+09,1.008785e+10,1.050634e+10,...,1.155671e+10,1.167190e+10,1.155963e+10,1.188324e+10,1.219576e+10,1.203023e+10,9.452937e+09,1.090899e+10,1.208520e+10,1.240413e+10
14,Bahrain,1.120777e+10,1.265021e+10,1.261858e+10,1.311449e+10,1.365350e+10,1.407580e+10,1.475003e+10,1.538429e+10,1.619966e+10,...,3.172761e+10,3.252330e+10,3.376406e+10,3.543668e+10,3.616404e+10,3.690645e+10,3.472477e+10,3.623532e+10,3.840266e+10,3.954736e+10
15,Bangladesh,5.767128e+10,6.038850e+10,6.273768e+10,6.595066e+10,6.893355e+10,7.202860e+10,7.575754e+10,7.929553e+10,8.349288e+10,...,1.831457e+11,1.951466e+11,2.090283e+11,2.228038e+11,2.391117e+11,2.579583e+11,2.668528e+11,2.853688e+11,3.056295e+11,3.232800e+11
16,Barbados,4.084033e+09,4.116422e+09,4.199195e+09,4.283766e+09,4.454109e+09,4.665239e+09,4.839180e+09,4.855375e+09,5.071303e+09,...,5.333182e+09,5.288058e+09,5.382816e+09,5.389730e+09,5.326451e+09,5.361211e+09,4.554115e+09,4.542503e+09,5.352562e+09,5.571686e+09
17,Belarus,2.629009e+10,2.429205e+10,2.144988e+10,1.921909e+10,1.975722e+10,2.200955e+10,2.385835e+10,2.466953e+10,2.610037e+10,...,5.870296e+10,5.645489e+10,5.502859e+10,5.642201e+10,5.819885e+10,5.904067e+10,5.864348e+10,6.007371e+10,5.727524e+10,5.950110e+10
18,Belgium,3.051405e+11,3.022054e+11,3.119575e+11,3.193970e+11,3.236176e+11,3.358946e+11,3.424842e+11,3.546175e+11,3.677976e+11,...,4.543469e+11,4.610448e+11,4.665473e+11,4.734264e+11,4.823172e+11,4.940997e+11,4.704176e+11,4.995955e+11,5.207455e+11,5.272637e+11
19,Belize,9.485521e+08,1.006774e+09,1.006575e+09,1.013952e+09,1.025168e+09,1.068585e+09,1.110158e+09,1.214789e+09,1.363484e+09,...,2.131737e+09,2.193050e+09,2.194246e+09,2.154468e+09,2.178395e+09,2.271361e+09,1.955576e+09,2.302615e+09,2.524886e+09,2.553898e+09
20,Benin,4.247544e+09,4.495438e+09,4.586264e+09,4.863513e+09,5.073825e+09,5.364793e+09,5.577293e+09,5.875202e+09,6.219354e+09,...,1.118920e+10,1.138816e+10,1.176849e+10,1.243595e+10,1.326881e+10,1.417981e+10,1.472556e+10,1.577924e+10,1.676595e+10,1.783106e+10
21,Bermuda,4.943721e+09,5.092456e+09,5.122991e+09,5.348359e+09,5.487442e+09,5.739864e+09,5.963719e+09,6.165450e+09,6.739895e+09,...,6.603330e+09,6.654541e+09,6.610807e+09,6.849551e+09,6.819906e+09,6.840793e+09,6.372687e+09,6.718028e+09,7.150074e+09,7.143294e+09
22,Bhutan,4.988870e+08,5.087967e+08,5.339898e+08,5.717649e+08,6.035846e+08,6.360202e+08,6.736347e+08,7.274175e+08,7.518228e+08,...,2.051190e+09,2.187816e+09,2.373254e+09,2.422780e+09,2.507623e+09,2.651940e+09,2.380954e+09,2.486225e+09,2.615853e+09,NaN
23,Bolivia,1.281260e+10,1.335961e+10,1.398314e+10,1.463730e+10,1.527569e+10,1.603248e+10,1.683881e+10,1.691069e+10,1.733478e+10,...,3.147157e+10,3.300020e+10,3.440730e+10,3.585076e+10,3.736496e+10,3.819323e+10,3.485595e+10,3.698613e+10,3.831973e+10,3.950073e+10
24,Bosnia and Herzegovina,2.985403e+09,2.920281e+09,3.245366e+09,3.763595e+09,5.803438e+09,7.929883e+09,9.247542e+09,1.012805e+10,1.067642e+10,...,1.572582e+10,1.640435e+10,1.693622e+10,1.748565e+10,1.815491e+10,1.867911e+10,1.811591e+10,1.945467e+10,2.027698e+10,2.072533e+10
25,Botswana,5.833041e+09,5.944808e+09,6.160481e+09,6.593588e+09,6.977981e+09,7.558960e+09,7.592496e+09,8.326481e+09,8.491986e+09,...,1.422064e+10,1.353075e+10,1.450556e+10,1.510237e+10,1.573487e+10,1.621199e+10,1.479688e+10,1.656077e+10,1.746929e+10,1.794687e+10
26,Brazil,9.216367e+11,9.670244e+11,1.023623e+12,1.066859e+12,1.090424e+12,1.127443e+12,1.131254e+12,1.136548e+12,1.186419e+12,...,1.868464e+12,1.802212e+12,1.743173e+12,1.766233e+12,1.797737e+12,1.819683e+12,1.760057e+12,1.843881e+12,1.899505e+12,1.954752e+12
27,Brunei,1.124483e+10,1.117358e+10,1.128450e+10,1.143654e+10,1.143341e+10,1.215874e+10,1.134932e+10,1.183288e+10,1.224403e+10,...,1.298123e+10,1.293030e+10,1.260989e+10,1.277745e+10,1.278414e+10,1.327874e+10,1.342926e+10,1.321563e+10,1.300044e+10,1.318336e+10
28,Bulgaria,3.279633e+10,3.231088e+10,3.289829e+10,3.383985e+10,3.560135e+10,3.057608e+10,3.173464e+10,2.907018e+10,3.040369e+10,...,4.914236e+10,5.081200e+10,5.234989e+10,5.378738e+10,5.515867e+10,5.724854e+10,5.540758e+10,5.971863e+10,6.213054e+10,6.330282e+10
29,Burkina Faso,3.325969e+09,3.441094e+09,3.486344e+09,3.685637e+09,4.091600e+09,4.350060e+09,4.667950e+09,5.013156e+09,5.107828e+09,...,1.138570e+10,1.183216e+10,1.253712e+10,1.331486e+10,1.419424e+10,1.503017e+10,1.533239e+10,1.639685e+10,1.664235e+10,1.713499e+10
30,Burundi,2.530356e+09,2.372462e+09,2.281597e+09,2.100894e+09,1.932823e+09,1.902091e+09,1.992440e+09,1.972317e+09,1.955417e+09,...,3.229972e+09,3.104004e+09,3.085379e+09,3.100806e+09,3.150727e+09,3.207836e+09,3.218331e+09,3.318099e+09,3.379451e+09,3.470696e+09
31,Cape Verde,3.527042e+08,3.834187e+08,4.569686e+08,5.219113e+08,5.811301e+08,6.457426e+08,7.265721e+08,8.081127e+08,9.235505e+08,...,1.733630e+09,1.749858e+09,1.824764e+09,1.907815e+09,1.978537e+09,2.116002e+09,1.675762e+09,1.793627e+09,2.077804e+09,2.191573e+09
32,Cambodia,6.997356e+09,7.284133e+09,4.748626e+09,5.218904e+09,5.526690e+09,5.748123e+09,6.017229e+09,6.781741e+09,7.459480e+09,...,2.254905e+10,2.417417e+10,2.608526e+10,2.819165e+10,3.066582e+10,3.309975e+10,3.192281e+10,3.290918e+10,3.458865e+10,3.630427e+10
33,Cameroon,1.436981e+10,1.322999e+10,1.347829e+10,1.386835e+10,1.445292e+10,1.510724e+10,1.582114e+10,1.653488e+10,1.716857e+10,...,3.048279e+10,3.221023e+10,3.367122e+10,3.486358e+10,3.624261e+10,3.750207e+10,3.759955e+10,3.885494e+10,4.030687e+10,4.161617e+10
34,Canada,8.671217e+11,8.901672e+11,9.301718e+11,9.551221e+11,9.712537e+11,1.012825e+12,1.052253e+12,1.106349e+12,1.163200e+12,...,1.546457e+12,1.556509e+12,1.572674e+12,1.620386e+12,1.664833e+12,1.696605e+12,1.611126e+12,1.696306e+12,1.761102e+12,1.783097e+12
35,Chad,2.931970e+09,2.471362e+09,2.721881e+09,2.755539e+09,2.816560e+09,2.975791e+09,3.182655e+09,3.160922e+09,3.133116e+09,...,1.065548e+10,1.095039e+10,1.026539e+10,9.958586e+09,1.019501e+10,1.052606e+10,1.035764e+10,1.023654e+10,1.052361e+10,1.095742e+10
36,Chile,8.603365e+10,9.170222e+10,9.631502e+10,1.049191e+11,1.120567e+11,1.203396e+11,1.253709e+11,1.250278e+11,1.312437e+11,...,2.373429e+11,2.424504e+11,2.467006e+11,2.500500e+11,2.600271e+11,2.616766e+11,2.456006e+11,2.734369e+11,2.790662e+11,2.796768e+11
37,China,1.282220e+12,1.460240e+12,1.650608e+12,1.831415e+12,2.013138e+12,2.199087e+12,2.371627e+12,2.553333e+12,2.770113e+12,...,1.033393e+13,1.106157e+13,1.181915e+13,1.264025e+13,1.349344e+13,1.429637e+13,1.461641e+13,1.585128e+13,1.631900e+13,1.717567e+13
38,Colombia,1.278713e+11,1.347577e+11,1.425934e+11,1.500118e+11,1.530958e+11,1.583474e+11,1.592497e+11,1.525548e+11,1.570168e+11,...,2.850661e+11,2.934924e+11,2.996187e+11,3.036916e+11,3.114792e+11,3.214056e+11,2.983097e+11,3.305307e+11,3.546227e+11,3.567873e+11
39,Comoros,5.431949e+08,5.595237e+08,5.299988e+08,5.491329e+08,5.420398e+08,5.638848e+08,5.711167e+08,5.821073e+08,6.452536e+08,...,9.550716e+08,9.660296e+08,9.981061e+08,1.036191e+09,1.073934e+09,1.092844e+09,1.090707e+09,1.112523e+09,1.141482e+09,1.175677e+09
40,Congo (Kinshasa),2.410105e+10,2.085487e+10,2.004153e+10,2.018182e+10,1.997532e+10,1.885330e+10,1.854709e+10,1.775510e+10,1.652806e+10,...,3.546490e+10,3.791771e+10,3.882750e+10,4.027458e+10,4.261902e+10,4.448766e+10,4.525971e+10,4.806588e+10,5.235549e+10,5.683758e+10
41,Congo (Brazzaville),5.912376e+09,5.854453e+09,5.532864e+09,5.753366e+09,6.000214e+09,5.962723e+09,6.185583e+09,6.025859e+09,6.482377e+09,...,1.238338e+10,1.243479e+10,1.135480e+10,1.071953e+10,1.047251e+10,1.059028e+10,9.926501e+09,1.002726e+10,1.017520e+10,1.036923e+10
42,Costa Rica,2.104620e+10,2.253989e+10,2.355847e+10,2.453708e+10,2.486844e+10,2.623028e+10,2.810714e+10,2.929180e+10,3.042502e+10,...,5.445324e+10,5.644192e+10,5.881492e+10,6.126027e+10,6.286278e+10,6.438249e+10,6.163120e+10,6.652211e+10,6.954986e+10,7.310519e+10
43,Ivory Coast,2.270074e+10,2.265704e+10,2.284084e+10,2.446842e+10,2.635966e+10,2.890307e+10,3.013547e+10,3.048710e+10,3.040607e+10,...,4.273989e+10,4.581501e+10,4.910121e+10,5.273998e+10,5.529425e+10,5.901079e+10,5.942370e+10,6.362099e+10,6.757685e+10,7.176662e+10
44,Croatia,3.246299e+10,2.985765e+10,3.161043e+10,3.374682e+10,3.580840e+10,3.801706e+10,3.887309e+10,3.854317e+10,3.967837e+10,...,4.984716e+10,5.100520e+10,5.277056e+10,5.450194e+10,5.608504e+10,5.782393e+10,5.301781e+10,5.971486e+10,6.406684e+10,6.618268e+10
45,Cuba,4.165341e+10,3.545614e+10,3.571033e+10,3.658781e+10,3.945584e+10,4.055406e+10,4.061860e+10,4.313239e+10,4.568356e+10,...,8.342990e+10,8.713280e+10,8.757965e+10,8.916466e+10,9.116904e+10,9.102035e+10,8.105446e+10,8.207063e+10,8.352727e+10,8.191603e+10
46,Cyprus,1.095698e+10,1.103368e+10,1.168467e+10,1.266179e+10,1.281989e+10,1.315845e+10,1.396254e+10,1.466038e+10,1.553492e+10,...,1.925110e+10,1.990928e+10,2.121803e+10,2.243825e+10,2.384550e+10,2.524656e+10,2.443346e+10,2.721589e+10,2.922051e+10,2.998372e+10
47,Czechia,1.081392e+11,1.082061e+11,1.113542e+11,1.182820e+11,1.232126e+11,1.224785e+11,1.219970e+11,1.236785e+11,1.286389e+11,...,1.801733e+11,1.891077e+11,1.939883e+11,2.040244e+11,2.097990e+11,2.172799e+11,2.057535e+11,2.140433e+11,2.201375e+11,2.199497e+11
48,Denmark,2.091676e+11,2.090026e+11,2.200686e+11,2.267544e+11,2.333206e+11,2.407133e+11,2.463130e+11,2.536219e+11,2.630668e+11,...,2.955395e+11,3.017589e+11,3.110321e+11,3.205387e+11,3.265008e+11,3.320885e+11,3.261770e+11,3.502556e+11,3.556501e+11,3.645243e+11
49,Djibouti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.254701e+09,2.424392e+09,2.597092e+09,2.738843e+09,2.869607e+09,3.028731e+09,3.068600e+09,3.207372e+09,3.326962e+09,3.549091e+09
50,Dominica,3.613718e+08,3.691826e+08,3.693099e+08,3.805032e+08,3.923148e+08,4.008893e+08,4.160198e+08,4.174928e+08,4.272630e+08,...,5.559221e+08,5.407370e+08,5.556811e+08,5.189006e+08,5.373090e+08,5.668744e+08,4.727499e+08,5.053250e+08,5.335401e+08,5.586817e+08
51,Dominican Republic,2.243324e+10,2.408534e+10,2.471164e+10,2.611660e+10,2.767781e+10,3.013705e+10,3.216060e+10,3.407096e+10,3.565926e+10,...,6.655458e+10,7.116483e+10,7.590384e+10,7.944604e+10,8.499338e+10,8.928739e+10,8.328707e+10,9.350805e+10,9.805097e+10,1.003656e+11
52,Ecuador,4.372086e+10,4.458356e+10,4.648204e+10,4.752907e+10,4.835216e+10,5.044477e+10,5.209257e+10,4.962370e+10,5.016549e+10,...,9.709334e+10,9.720956e+10,9.654080e+10,1.023047e+11,1.033730e+11,1.035440e+11,9.397127e+10,1.031978e+11,1.095817e+11,1.121626e+11
53,Egypt,1.216715e+11,1.252009e+11,1.301753e+11,1.362187e+11,1.430143e+11,1.508691e+11,1.592808e+11,1.689228e+11,1.796832e+11,...,3.155698e+11,3.293666e+11,3.436830e+11,3.580531e+11,3.771413e+11,3.980805e+11,4.122131e+11,4.257775e+11,4.538271e+11,4.708851e+11
54,El Salvador,1.377277e+10,1.457411e+10,1.525794e+10,1.598026e+10,1.610994e+10,1.661546e+10,1.705615e+10,1.742491e+10,1.762145e+10,...,2.288891e+10,2.343824e+10,2.403335e+10,2.457353e+10,2.516635e+10,2.577978e+10,2.374495e+10,2.657173e+10,2.731562e+10,2.827467e+10
55,Equatorial Guinea,2.317046e+08,2.572690e+08,3.001528e+08,3.526383e+08,5.874249e+08,1.468403e+09,1.817509e+09,2.283954e+09,2.699949e+09,...,1.450710e+10,1.318550e+10,1.202301e+10,1.134160e+10,1.063428e+10,1.005133e+10,9.569760e+09,9.652085e+09,9.963221e+09,9.456162e+09
56,Eritrea,1.154926e+09,1.310319e+09,1.588387e+09,1.633789e+09,1.785059e+09,1.926234e+09,1.960378e+09,1.960642e+09,1.899039e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Estonia,1.063071e+10,1.002046e+10,9.855880e+09,1.030202e+10,1.081126e+10,1.222213e+10,1.275255e+10,1.269834e+10,1.397931e+10,...,2.289107e+10,2.331185e+10,2.403289e+10,2.538706e+10,2.632631e+10,2.730740e+10,2.651990e+10,2.841725e+10,2.843443e+10,2.757484e+10
58,Eswatini,1.863494e+09,1.921376e+09,1.967502e+09,2.062447e+09,2.141687e+09,2.208140e+09,2.265641e+09,2.332497e+09,2.373553e+09,...,3.826332e+09,3.878174e+09,4.015035e+09,4.114008e+09,4.145652e+09,4.351364e+09,4.225737e+09,4.369385e+09,4.366430e+09,4.585402e+09
59,Ethiopia,1.121558e+10,1.268962e+10,1.309442e+10,1.389678e+10,1.562362e+10,1.611325e+10,1.555603e+10,1.635905e+10,1.735257e+10,...,5.850882e+10,6.458933e+10,7.068235e+10,7.744255e+10,8.272114e+10,8.964001e+10,9.507178e+10,1.004353e+11,1.057796e+11,1.126533e+11

In [385]:
df_long = df_filtered.melt(
    id_vars='Country',
    var_name='Year',
    value_name='GDP'
)

# Convert Year to integer (if needed)
df_long['Year'] = df_long['Year'].astype(int)

# Optional: sort it nicely
df_long = df_long.sort_values(by=['Country', 'Year']).reset_index(drop=True)

# Reorder columns
df_long = df_long[['Year', 'Country', 'GDP']]

# Preview
print(df_long.head(10))

   Year      Country           GDP
0  1992  Afghanistan           NaN
1  1993  Afghanistan           NaN
2  1994  Afghanistan           NaN
3  1995  Afghanistan           NaN
4  1996  Afghanistan           NaN
5  1997  Afghanistan           NaN
6  1998  Afghanistan           NaN
7  1999  Afghanistan           NaN
8  2000  Afghanistan  6.206548e+09
9  2001  Afghanistan  5.621148e+09

In [386]:
save_path = Path(r"C:\Users\snaja\OneDrive\defaidtics\data\clean\wb\gdp_long_1992-2023.csv")

# Make sure the folder exists
save_path.parent.mkdir(parents=True, exist_ok=True)

# Save sorted dataframe
df_long.to_csv(save_path, index=False)

print(f"Cleaned and sorted file written to: {save_path}")

Cleaned and sorted file written to: C:\Users\snaja\OneDrive\defaidtics\data\clean\wb\gdp_long_1992-2023.csv

In [387]:
# Assume the first column is 'Country' and all others are years (e.g., 1990–2023)
year_columns = df_filtered.columns[1:]  # Skip 'Country' column

# Count number of missing year values per country
df_filtered["Missing_Years"] = df_filtered[year_columns].isna().sum(axis=1)

# View countries sorted by how many years are missing
missing_summary = df_filtered[["Country", "Missing_Years"]].sort_values(by="Missing_Years", ascending=False)

missing_summary.head(60)

                      Country  Missing_Years
91                North Korea             32
188                 Venezuela             32
162  St. Martin (French part)             32
101             Liechtenstein             31
157               South Sudan             24
49                   Djibouti             21
179  Turks and Caicos Islands             19
56                    Eritrea             12
1                 Afghanistan              8
144                San Marino              6
116                Montenegro              5
190                     Yemen              5
148                    Serbia              3
97                    Lebanon              1
174                     Tonga              1
22                     Bhutan              1
168                     Syria              1
16                   Barbados              0
17                    Belarus              0
19                     Belize              0
0        United Arab Emirates              0
5                      Angola              0
6         Antigua and Barbuda              0
3                     Algeria              0
2                     Albania              0
9                       Aruba              0
10                  Australia              0
11                    Austria              0
12                 Azerbaijan              0
13                The Bahamas              0
14                    Bahrain              0
7                   Argentina              0
4                     Andorra              0
32                   Cambodia              0
31                 Cape Verde              0
33                   Cameroon              0
34                     Canada              0
37                      China              0
38                   Colombia              0
35                       Chad              0
36                      Chile              0
41        Congo (Brazzaville)              0
42                 Costa Rica              0
43                Ivory Coast              0
44                    Croatia              0
45                       Cuba              0
46                     Cyprus              0
39                    Comoros              0
40           Congo (Kinshasa)              0
48                    Denmark              0
47                    Czechia              0
51         Dominican Republic              0
18                    Belgium              0
20                      Benin              0
21                    Bermuda              0
23                    Bolivia              0
24     Bosnia and Herzegovina              0
25                   Botswana              0
26                     Brazil              0
27                     Brunei              0

In [388]:
# Step 1: Count missing years per country (across all year columns)
missing_years_per_country = df_filtered.set_index('Country').isna().sum(axis=1)

# Step 2: Identify countries with more than 5 missing years
countries_to_drop = missing_years_per_country[missing_years_per_country > 5].index.tolist()
print(f"Number of countries to drop: {len(countries_to_drop)}")

# Step 3: Drop these countries from df_filtered
df_final = df_filtered[~df_filtered['Country'].isin(countries_to_drop)].reset_index(drop=True)

# Step 4: Check result
print(f"Remaining countries: {df_final['Country'].nunique()}")
df_final.head(10)

Number of countries to drop: 10
Remaining countries: 183

,Country,1992,1993,1994,1995,1996,1997,1998,1999,2000,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Missing_Years
0,United Arab Emirates,1.325241e+11,1.341955e+11,1.434498e+11,1.530435e+11,1.619176e+11,1.751793e+11,1.756908e+11,1.807897e+11,2.004103e+11,...,3.702755e+11,3.908683e+11,3.937415e+11,3.989149e+11,4.033362e+11,3.833427e+11,4.000363e+11,4.300778e+11,4.456411e+11,0
1,Albania,3.527709e+09,3.864937e+09,4.185838e+09,4.743489e+09,5.175147e+09,4.610021e+09,5.017060e+09,5.663799e+09,6.057219e+09,...,1.138685e+10,1.176433e+10,1.221168e+10,1.270250e+10,1.296450e+10,1.253490e+10,1.365922e+10,1.431851e+10,1.488217e+10,0
2,Algeria,9.202645e+10,9.009389e+10,8.928305e+10,9.267580e+10,9.647551e+10,9.753674e+10,1.025111e+11,1.057915e+11,1.098116e+11,...,1.874939e+11,1.948061e+11,1.977282e+11,2.004964e+11,2.023009e+11,1.921858e+11,1.994889e+11,2.066705e+11,2.151440e+11,0
3,Andorra,1.695349e+09,1.677862e+09,1.717848e+09,1.765218e+09,1.847296e+09,2.014803e+09,2.079171e+09,2.164398e+09,2.240766e+09,...,2.789881e+09,2.893377e+09,2.903390e+09,2.949518e+09,3.008967e+09,2.672446e+09,2.893906e+09,3.170697e+09,3.252613e+09,0
4,Angola,2.631549e+10,2.000414e+10,2.027207e+10,2.331287e+10,2.647046e+10,2.839599e+10,2.972809e+10,3.037660e+10,3.130450e+10,...,9.049642e+10,8.816157e+10,8.803178e+10,8.687297e+10,8.626288e+10,8.139919e+10,8.237534e+10,8.488345e+10,8.573337e+10,0
5,Antigua and Barbuda,8.581153e+08,9.034261e+08,9.637381e+08,9.217252e+08,9.826039e+08,1.036364e+09,1.085397e+09,1.125640e+09,1.195469e+09,...,1.437756e+09,1.496700e+09,1.533569e+09,1.640201e+09,1.691054e+09,1.371776e+09,1.484149e+09,1.625386e+09,1.688159e+09,0
6,Argentina,3.131202e+11,3.388180e+11,3.585921e+11,3.483894e+11,3.676438e+11,3.974635e+11,4.127666e+11,3.987925e+11,3.956461e+11,...,5.947493e+11,5.823766e+11,5.987909e+11,5.831181e+11,5.714507e+11,5.148743e+11,5.686366e+11,5.986030e+11,5.889595e+11,0
7,Armenia,3.001096e+09,2.737000e+09,2.884798e+09,3.083849e+09,3.264729e+09,3.373153e+09,3.619394e+09,3.738834e+09,3.959425e+09,...,1.055334e+10,1.057444e+10,1.136753e+10,1.195864e+10,1.286750e+10,1.194104e+10,1.263362e+10,1.422545e+10,1.540616e+10,0
8,Aruba,1.908830e+09,2.048322e+09,2.216364e+09,2.272818e+09,2.299769e+09,2.461831e+09,2.510870e+09,2.541956e+09,2.735727e+09,...,2.962907e+09,3.013858e+09,3.226291e+09,3.303628e+09,3.229876e+09,2.383267e+09,2.958412e+09,3.210407e+09,3.347290e+09,0
9,Australia,6.297462e+11,6.552303e+11,6.813110e+11,7.077863e+11,7.351344e+11,7.639020e+11,7.995244e+11,8.397219e+11,8.726517e+11,...,1.351296e+12,1.388584e+12,1.420238e+12,1.461119e+12,1.492848e+12,1.491063e+12,1.522541e+12,1.587133e+12,1.641762e+12,0

In [389]:
df_final = df_final.drop(columns=['Country Code', '2024', 'Missing_Years'], errors='ignore')
df_final = df_final.reset_index(drop=True)

In [390]:
df_final.shape

(183, 33)

In [391]:
# Create a copy to preserve df_final
df_final_interpolated = df_final.copy()

# Identify year columns (excluding 'Country')
year_cols = df_final_interpolated.columns.difference(['Country'])

# Interpolate only missing values for each country across years
df_final_interpolated[year_cols] = df_final_interpolated[year_cols].apply(
    lambda row: row.interpolate(limit_direction='both'), axis=1
)

# Confirm if any NaNs remain (there shouldn't be, since we dropped >5-missing already)
missing_remaining = df_final_interpolated[year_cols].isna().sum().sum()
print(f"Total remaining missing values after interpolation: {missing_remaining}")

Total remaining missing values after interpolation: 0

In [392]:
df_final_interpolated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183 entries, 0 to 182
Data columns (total 33 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  183 non-null    object
 1   1992     183 non-null    float64
 2   1993     183 non-null    float64
 3   1994     183 non-null    float64
 4   1995     183 non-null    float64
 5   1996     183 non-null    float64
 6   1997     183 non-null    float64
 7   1998     183 non-null    float64
 8   1999     183 non-null    float64
 9   2000     183 non-null    float64
 10  2001     183 non-null    float64
 11  2002     183 non-null    float64
 12  2003     183 non-null    float64
 13  2004     183 non-null    float64
 14  2005     183 non-null    float64
 15  2006     183 non-null    float64
 16  2007     183 non-null    float64
 17  2008     183 non-null    float64
 18  2009     183 non-null    float64
 19  2010     183 non-null    float64
 20  2011     183 non-null    float64
 21  2012     183 non-null    float64
 22  2013     183 non-null    float64
 23  2014     183 non-null    float64
 24  2015     183 non-null    float64
 25  2016     183 non-null    float64
 26  2017     183 non-null    float64
 27  2018     183 non-null    float64
 28  2019     183 non-null    float64
 29  2020     183 non-null    float64
 30  2021     183 non-null    float64
 31  2022     183 non-null    float64
 32  2023     183 non-null    float64
dtypes: float64(32), object(1)
memory usage: 47.3+ KB

In [393]:
unique_countries = df_final_interpolated['Country'].unique()
print(unique_countries)

['United Arab Emirates' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba' 'Australia' 'Austria'
 'Azerbaijan' 'The Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Brunei' 'Bulgaria'
 'Burkina Faso' 'Burundi' 'Cape Verde' 'Cambodia' 'Cameroon' 'Canada'
 'Chad' 'Chile' 'China' 'Colombia' 'Comoros' 'Congo (Kinshasa)'
 'Congo (Brazzaville)' 'Costa Rica' 'Ivory Coast' 'Croatia' 'Cuba'
 'Cyprus' 'Czechia' 'Denmark' 'Dominica' 'Dominican Republic' 'Ecuador'
 'Egypt' 'El Salvador' 'Equatorial Guinea' 'Estonia' 'Eswatini' 'Ethiopia'
 'Fiji' 'Finland' 'France' 'Gabon' 'The Gambia' 'Georgia' 'Germany'
 'Ghana' 'Greece' 'Grenada' 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana'
 'Haiti' 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan'
 'Kenya' 'Kiribati' 'South Korea' 'Kuwait' 'Kyrgyz Republic' 'Laos'
 'Latvia' 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Lithuania' 'Luxembourg'
 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Mauritania'
 'Mauritius' 'Mexico' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'North Macedonia' 'Norway'
 'Oman' 'Pakistan' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Qatar' 'Romania' 'Russia' 'Rwanda'
 'Samoa' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia'
 'Solomon Islands' 'Somalia' 'South Africa' 'Spain' 'Sri Lanka'
 'St. Kitts and Nevis' 'St. Lucia' 'St. Vincent and the Grenadines'
 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Tajikistan' 'Tanzania'
 'Thailand' 'Timor Leste' 'Togo' 'Tonga' 'Trinidad and Tobago' 'Tunisia'
 'Türkiye' 'Turkmenistan' 'Tuvalu' 'Uganda' 'Ukraine' 'United Kingdom'
 'United States' 'Uruguay' 'Uzbekistan' 'Vanuatu' 'Vietnam' 'Yemen'
 'Zambia' 'Zimbabwe']

In [394]:
df_final_interpolated.isna().sum().sum()

np.int64(0)

In [395]:
save_path = Path(r"C:\Users\snaja\OneDrive\defaidtics\data\clean\wb\gdp_complete_wide_1992-2023.csv")

# Make sure the folder exists
save_path.parent.mkdir(parents=True, exist_ok=True)

# Save sorted dataframe
df_final_interpolated.to_csv(save_path, index=False)

print(f"Cleaned and sorted file written to: {save_path}")

Cleaned and sorted file written to: C:\Users\snaja\OneDrive\defaidtics\data\clean\wb\gdp_complete_wide_1992-2023.csv

In [396]:
df_long = df_final_interpolated.melt(
    id_vars='Country',
    var_name='Year',
    value_name='GDP'
)

# Convert Year to integer (if needed)
df_long['Year'] = df_long['Year'].astype(int)

# Optional: sort it nicely
df_long = df_long.sort_values(by=['Country', 'Year']).reset_index(drop=True)

# Reorder columns
df_long = df_long[['Year', 'Country', 'GDP']]

# Preview
print(df_long.head(10))

   Year  Country           GDP
0  1992  Albania  3.527709e+09
1  1993  Albania  3.864937e+09
2  1994  Albania  4.185838e+09
3  1995  Albania  4.743489e+09
4  1996  Albania  5.175147e+09
5  1997  Albania  4.610021e+09
6  1998  Albania  5.017060e+09
7  1999  Albania  5.663799e+09
8  2000  Albania  6.057219e+09
9  2001  Albania  6.559563e+09

In [397]:
df_long['GDP'] = df_long['GDP'] / 1_000_000
df_long.head(50)

    Year  Country            GDP
0   1992  Albania    3527.709062
1   1993  Albania    3864.937294
2   1994  Albania    4185.837882
3   1995  Albania    4743.489157
4   1996  Albania    5175.146643
5   1997  Albania    4610.021454
6   1998  Albania    5017.059783
7   1999  Albania    5663.799109
8   2000  Albania    6057.218862
9   2001  Albania    6559.562959
10  2002  Albania    6857.139117
11  2003  Albania    7236.245480
12  2004  Albania    7635.300387
13  2005  Albania    8057.259479
14  2006  Albania    8532.852034
15  2007  Albania    9043.394715
16  2008  Albania    9721.653066
17  2009  Albania   10047.745439
18  2010  Albania   10420.209148
19  2011  Albania   10685.445792
20  2012  Albania   10836.884503
21  2013  Albania   10945.471987
22  2014  Albania   11139.693789
23  2015  Albania   11386.853113
24  2016  Albania   11764.325094
25  2017  Albania   12211.675170
26  2018  Albania   12702.504600
27  2019  Albania   12964.502337
28  2020  Albania   12534.895530
29  2021  Albania   13659.219677
30  2022  Albania   14318.507637
31  2023  Albania   14882.173625
32  1992  Algeria   92026.450046
33  1993  Algeria   90093.893897
34  1994  Algeria   89283.051958
35  1995  Algeria   92675.803281
36  1996  Algeria   96475.509798
37  1997  Algeria   97536.740347
38  1998  Algeria  102511.117625
39  1999  Algeria  105791.474982
40  2000  Algeria  109811.551032
41  2001  Algeria  113105.897562
42  2002  Algeria  119213.616031
43  2003  Algeria  126962.501073
44  2004  Algeria  132675.813621
45  2005  Algeria  139840.307556
46  2006  Algeria  143895.676475
47  2007  Algeria  148356.442446
48  2008  Algeria  152065.353507
49  2009  Algeria  153890.137749

In [398]:
unique_countries = df_long['Country'].unique()
print(unique_countries)

['Albania' 'Algeria' 'Andorra' 'Angola' 'Antigua and Barbuda' 'Argentina'
 'Armenia' 'Aruba' 'Australia' 'Austria' 'Azerbaijan' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Brunei'
 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon' 'Canada'
 'Cape Verde' 'Chad' 'Chile' 'China' 'Colombia' 'Comoros'
 'Congo (Brazzaville)' 'Congo (Kinshasa)' 'Costa Rica' 'Croatia' 'Cuba'
 'Cyprus' 'Czechia' 'Denmark' 'Dominica' 'Dominican Republic' 'Ecuador'
 'Egypt' 'El Salvador' 'Equatorial Guinea' 'Estonia' 'Eswatini' 'Ethiopia'
 'Fiji' 'Finland' 'France' 'Gabon' 'Georgia' 'Germany' 'Ghana' 'Greece'
 'Grenada' 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Israel' 'Italy' 'Ivory Coast' 'Jamaica' 'Japan' 'Jordan'
 'Kazakhstan' 'Kenya' 'Kiribati' 'Kuwait' 'Kyrgyz Republic' 'Laos'
 'Latvia' 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Lithuania' 'Luxembourg'
 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Mauritania'
 'Mauritius' 'Mexico' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'North Macedonia' 'Norway'
 'Oman' 'Pakistan' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Qatar' 'Romania' 'Russia' 'Rwanda'
 'Samoa' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia'
 'Solomon Islands' 'Somalia' 'South Africa' 'South Korea' 'Spain'
 'Sri Lanka' 'St. Kitts and Nevis' 'St. Lucia'
 'St. Vincent and the Grenadines' 'Sudan' 'Suriname' 'Sweden'
 'Switzerland' 'Syria' 'Tajikistan' 'Tanzania' 'Thailand' 'The Bahamas'
 'The Gambia' 'Timor Leste' 'Togo' 'Tonga' 'Trinidad and Tobago' 'Tunisia'
 'Turkmenistan' 'Tuvalu' 'Türkiye' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Vietnam' 'Yemen' 'Zambia' 'Zimbabwe']

In [399]:
df_long['Year'] = df_long['Year'].astype(int)

In [400]:
save_path = Path(r"C:\Users\snaja\OneDrive\defaidtics\data\clean\wb\gdp_complete_long_1992-2023.csv")

# Make sure the folder exists
save_path.parent.mkdir(parents=True, exist_ok=True)

# Save sorted dataframe
df_long.to_csv(save_path, index=False)

print(f"Cleaned and sorted file written to: {save_path}")

Cleaned and sorted file written to: C:\Users\snaja\OneDrive\defaidtics\data\clean\wb\gdp_complete_long_1992-2023.csv